export const ACCESS_TOKEN_COOKIE_NAME = 'accessToken';
export const REFRESH_TOKEN_COOKIE_NAME = 'refreshToken';
export const JWT_ACCESS_SECRET_KEY = 'JWT_ACCESS_SECRET_KEY';
export const JWT_ACCESS_EXPIRATION = 'JWT_ACCESS_EXPIRATION';
export const JWT_REFRESH_SECRET_KEY = 'JWT_REFRESH_SECRET_KEY';
export const JWT_REFRESH_EXPIRATION = 'JWT_REFRESH_EXPIRATION';
